title: ZFB
SEOTitle: WHUZFB的个人博客
author: 晨曦
timezone: Asia/Shanghai
paginate: 10
paginate_path: "page:num"
highlighter: rouge
url: "https://blog.whuzfb.cn"
baseurl: ""
markdown: kramdown
kramdown:
  input: GFM

gems: [jekyll-paginate, jekyll-sitemap, jekyll-feed]

disqus: zfb132
disqus_base: http://blog.whuzfb.cn/

# https://support.google.com/analytics/answer/11583528
google_analytics_id: UA-97824262-2
# Google Analytics 4
google_analytics_measurement_id: G-DYVCXMX74E

# use google translate
google_translate: true

# https://www.bing.com/webmasters/clarity
microsoft_clarity_id: bymgg301ca

# auto push url to baidu
baidu_push: true

# use progress indicator
progress_indicator: true

permalink: /blog/:year/:month/:day/:title/

header-img: /img/default-bg.jpg
WeChatPublic: /img/qrcode_WeChatPublic.jpg

RSS: feed.xml
categories_path: categories
tags_path: tags
archive_path: archives
about_path: about

BASE_PATH:

zhihu_username: zfb-chenxi
weibo_username:     zfb132
facebook_username:
github_username:    zfb132
google_username:
email: admin@whuzfb.cn
linkedin:

#  default.html footer
anchorjs: true

# page Sidebar settings
sidebar-about-description: "在代码的道路上渐行渐远"
sidebar-avatar: /img/me2.jpg

# Friends
friends: [
  {
    title: "Monlor's Blog",
    href: "https://www.monlor.com"
  },
  {
    title: "CSDN",
    href: "https://blog.csdn.net/qq_32507255/"
  },
  {
    title: "博客园",
    href: "https://www.cnblogs.com/zfb132/"
  },
  {
    title: "简书",
    href: "https://www.jianshu.com/u/8ee7e271d4f5/"
  },
  {
    title: "OSCHINA",
    href: "https://my.oschina.net/zfb132"
  },
  {
    title: "GitHub下载加速",
    href: "https://ghapi.zfb132.workers.dev/"
  },
  {
    title: "brucezhaor",
    href: "https://github.com/BruceZhaoR"
  }
]
